pipeline {
  environment {
    IMAGE_NAME='productpage'
    VERSION="v${env.BUILD_NUMBER}"
    REPO='evgenil'
    CREDENTIALS_ID='evgenil'
    SNYK_TOKEN='eeca44ef-5c1a-4a54-be67-ad9cad2d79e5'
  }
  agent any
  stages {
    stage('Security') {
      steps {
        script {
          sh 'docker build --target security --build-arg SNYK_TOKEN=${SNYK_TOKEN} --tag ${REPO}/${IMAGE_NAME}:${VERSION}-security -f welcome/app/bookinfo/src/reviews/Dockerfile welcome/app/bookinfo/src/reviews/'
          sh 'docker run --rm ${REPO}/${IMAGE_NAME}:${VERSION}-security'
        }
      }
    }
  }
}
