pipeline {
  environment {
    IMAGE_NAME='productpage'
    VERSION="v${env.BUILD_NUMBER}"
    REPO='evgenil'
    CREDENTIALS_ID='evgenil'
    SNYK_TOKEN='d2be5c6a-7f38-4845-a18e-bf617b1116ab'
  }
  agent any
  stages {
    stage('Security') {
      steps {
        script {
          sh 'docker build --target security --build-arg SNYK_TOKEN=${SNYK_TOKEN} --tag ${REPO}/${IMAGE_NAME}:${VERSION}-security -f welcome/app/bookinfo/src/reviews/Dockerfile welcome/app/bookinfo/src/reviews/'
          sh 'docker run --rm ${REPO}/${IMAGE_NAME}:${VERSION}-security'
        }
      }
    }
  }
}
