pipeline {
    environment {
        IMAGE_NAME='productpage'
        VERSION="v${env.BUILD_NUMBER}"
        REPO='productpage'
        CREDENTIALS_ID='evgenil'
    }
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    //BuildtheDockerimageforthebuildstage
                    sh'docker build --target build --tag ${IMAGE_NAME}:${VERSION}-build.'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    //BuildandtesttheDockerimage
                    sh'docker build --target test --tag ${IMAGE_NAME}:${VERSION}-test.'
                    sh'docker run --rm ${IMAGE_NAME}:${VERSION}-test'
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/',"${CREDENTIALS_ID}") {
                        sh'docker push ${REPO}/${IMAGE_NAME}:${VERSION}'
                        //Continuewithcreatingalatestversionalso-usingdockertagandpushit
                    }
                }
            }
        }
    }
}
